"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./pyaroma_main.py']
DATA_FILES = ['./assets']
OPTIONS = {'iconfile': './assets/pyAroma3.icns'}

setup(
    name='py.Aroma 3',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
